import { test, expect, type Page } from '@playwright/test'
import { resolve } from 'node:path'

const image = resolve(import.meta.dirname, '../../tests/fixtures/ba/v2.1/images/creative-pass.png')
async function fillPlan(page: Page, title: string, budget: string) {
  await page.goto('/plans/new')
  await page.getByLabel('Tên chiến dịch').fill(title)
  await page.getByLabel('Mục tiêu').fill('Synthetic browser campaign')
  await page.getByLabel('Ngày bắt đầu').fill('2026-10-01')
  await page.getByLabel('Ngày kết thúc').fill('2026-10-31')
  await page.getByLabel('Ngân sách').fill(budget)
  await page.getByLabel('Tóm tắt').fill('Browser smoke strategy')
  await page.getByLabel('Ảnh đính kèm', { exact: true }).setInputFiles(image)
}

test('Maker saves, uploads, submits and observes persisted auto approval', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await fillPlan(page, 'E2E auto campaign', '50000000')
  await page.getByRole('button', { name: 'Lưu draft' }).click()
  await expect(page).toHaveURL(/\/edit$/)
  await expect(page.getByText('1 ảnh đã lưu trên backend')).toBeVisible()
  await page.getByRole('button', { name: 'Gửi duyệt', exact: true }).click()
  await expect(page).toHaveURL(/\/result$/)
  await expect(page.getByText('APPROVED · AUTO_APPROVED')).toBeVisible()
  const id = page.url().split('/').at(-2)!
  const response = await request.get(`http://127.0.0.1:8008/api/plans/${id}`, { headers: { 'X-Demo-Actor': 'DEMO-MAKER-01' } })
  const history = await response.json()
  expect(history.plan.state.plan_status).toBe('APPROVED')
  expect(history.versions).toHaveLength(1)
  expect(history.audit.some((e: { action: string }) => e.action === 'AUTO_APPROVED')).toBeTruthy()
  await page.getByRole('link', { name: 'Version / round / history' }).click()
  await expect(page.getByText('Version 1 / Round 1', { exact: true })).toBeVisible()
  await expect(page.getByRole('img')).toBeVisible()
  await page.screenshot({ path: 'test-results/auto-history.png', fullPage: true })
  expect(errors).toEqual([])
})

test('Human Review: Checker rejects, Maker resubmits and history preserves both rounds', async ({ page, request }) => {
  await fillPlan(page, 'E2E budget review', '100000001')
  await page.getByRole('button', { name: 'Gửi duyệt', exact: true }).click()
  await expect(page).toHaveURL(/\/result$/)
  await expect(page.getByText('PENDING_APPROVAL · AUTHORITY_EXCEEDED')).toBeVisible()
  const id = page.url().split('/').at(-2)!
  await page.getByLabel('Demo actor').selectOption('DEMO-CHECKER-01')
  await page.getByRole('link', { name: 'Review Queue' }).click()
  await page.getByText('E2E budget review', { exact: true }).click()
  await page.locator('#review-reason').fill('Reduce budget and resubmit')
  await page.getByLabel('Lý do override').fill('Budget exceeds approved mandate despite model recommendation')
  await page.getByRole('button', { name: 'Reject', exact: true }).click()
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText(/Quyết định đã được lưu/)
  await page.getByLabel('Demo actor').selectOption('DEMO-MAKER-01')
  await page.getByRole('link', { name: 'E2E budget review' }).click()
  await page.getByRole('link', { name: 'Sửa và gửi lại' }).click()
  await page.getByLabel('Ngân sách').fill('50000000')
  await page.getByRole('button', { name: 'Gửi duyệt', exact: true }).click()
  await expect(page).toHaveURL(/\/result$/)
  await expect(page.getByText('APPROVED · AUTO_APPROVED')).toBeVisible()
  const response = await request.get(`http://127.0.0.1:8008/api/plans/${id}`, { headers: { 'X-Demo-Actor': 'DEMO-MAKER-01' } })
  const history = await response.json()
  expect(history.versions).toHaveLength(2)
  expect(history.versions[0].payload.budget_minor_units).toBe('100000001')
  expect(history.versions[1].payload.budget_minor_units).toBe('50000000')
  expect(history.records.filter((r: { kind: string }) => r.kind === 'human_decision')).toHaveLength(1)
})

test('factual evidence and real Verify results render', async ({ page }) => {
  await page.goto('/plans/DEMO-SEED-FACTS/result')
  await expect(page.getByText('PENDING_APPROVAL · FACT_UNCERTAIN')).toBeVisible()
  await expect(page.getByText(/form KPI 1200; visual evidence 12000/)).toBeVisible()
  await page.screenshot({ path: 'test-results/factual-review.png', fullPage: true })
  await page.getByRole('link', { name: 'Verify', exact: true }).click()
  await page.getByRole('button', { name: 'Run all 5' }).click()
  await expect(page.getByText('5/5 PASS', { exact: true })).toBeVisible()
})

test('Checker approves a review with an explicit override and persisted audit', async ({ page, request }) => {
  await page.goto('/plans')
  await page.getByLabel('Demo actor').selectOption('DEMO-CHECKER-01')
  await page.getByRole('link', { name: 'Review Queue' }).click()
  await page.getByText('Demo review', { exact: true }).click()
  await page.locator('#review-reason').fill('Evidence inspected manually')
  await page.getByLabel('Lý do override').fill('Manual review resolves mock recommendation')
  await page.screenshot({ path: 'test-results/checker-review.png', fullPage: true })
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText(/Quyết định đã được lưu/)
  const response = await request.get('http://127.0.0.1:8008/api/plans/DEMO-SEED-REVIEW', { headers: { 'X-Demo-Actor': 'DEMO-CHECKER-01' } })
  const history = await response.json()
  expect(history.plan.state.plan_status).toBe('APPROVED')
  expect(history.audit.some((e: { action: string; override_reason: string }) => e.action === 'HUMAN_APPROVED' && e.override_reason === 'Manual review resolves mock recommendation')).toBeTruthy()
})
